package com.devguard.shared.audit;

public enum AuditAction {
    PROJECT_CREATE,
    PROJECT_READ,
    PROJECT_UPDATE,
    REPOSITORY_CONNECT,
    REPOSITORY_REVOKE,
    SCAN_REQUEST,
    TENANT_RESOLUTION_FAILED,
    CROSS_TENANT_ACCESS_ATTEMPT
}
